[package]
name = "client"
version = "0.1.0"
rust-version = "1.56"
edition = "2021"

[dependencies]
#anchor-client = "0.28.0"
#anchor-lang = "0.28.0"
anchor-client = {git = " https://github.com/acheroncrypto/anchor", branch = "replace-pubsubclienterror-unexpectedmessage"}
anchor-lang = {git = " https://github.com/acheroncrypto/anchor", branch = "replace-pubsubclienterror-unexpectedmessage"}
raydium-amm-v3 = {path = "../programs/amm", features = ["no-entrypoint", "client"]}
solana-sdk = ">=1.14, <1.17"
solana-client = ">=1.14, <1.17"
solana-account-decoder = ">=1.14, <1.17"
solana-transaction-status = ">=1.14, <1.17"
spl-token = { version = "3.5.0", features=["no-entrypoint"] }
spl-token-client = "0.5.0"
spl-memo = "=3.0.1"
spl-associated-token-account = "1.0.3"
spl-token-2022 = { version = "0.6.1", features = ["no-entrypoint"]}
mpl-token-metadata = { version = "1.11.0", features = ["no-entrypoint"] }
clap = { version = "4.1.8", features = ["derive"] }
shellexpand = "2.1.0"
anyhow = "1.0.32"
rand = "0.7.3"
hex = "0.4.3"
configparser = "3.0.0"
borsh = "0.9.3"
serde_json = { version = "1.0.78" }
serde = { version = "1.0", features = ["derive"] }
arrayref = "0.3.7"
bs58 = { version = "0.4.0"}
bincode = { version = "1.3.3" }
regex = "1"
colorful = "0.2.2"